# Generated by Django 4.1.6 on 2023-02-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Title', help_text='the title of the movie ', max_length=50)),
                ('description', models.CharField(default='description ', max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
