# Generated by Django 4.1.4 on 2023-02-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='plateform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='WatchList', to='watchlist_app.streamplatform'),
            preserve_default=False,
        ),
    ]
